name: tea-gui
channels:
  - conda-forge
dependencies:
  - python=3.10
  - reaktoro
  - streamlit>=1.37
  - pandas
  - numpy
  - pydeck
  - openpyxl
  - matplotlib
  - pip
  - pip:
      - folium
      - streamlit-folium
